server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees/**,/api/departments/**
              filters:
                - StripPrefix=1
            - id: leave-service
              uri: lb://LEAVE-SERVICE
              predicates:
                - Path=/api/leaves/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
